### ISSUE TITLE
Use stdout as default output for ConsoleHandler

### ISSUE THREAD

**Issue by hgfischer** [twitter/util#120]
Currently stderr is used for all logs sent to ConsoleHandler. This is not a good practice. Please, consider using stdout for everything and stderr only for ERROR levels.

cheers

**Comment by vkostyukov** [comment]
Hi @hgfischer! Sorry for the delay. Do you mind submitting a PR?

**Comment by mosesn** [comment]
I think the idea here is that logging handlers are typically used for diagnostics and errors, and that we only want the actual output of a program (for example, if you wanted to implement curl with finagle, the content of the http response) to go to stdout.  I'm going to close this issue for now since it hasn't seen movement in a year and a half, but feel free to reopen if you want to continue discussing it.
