### ISSUE TITLE
Failing builds because of twitter dependencies

### ISSUE THREAD

**Issue by alexflav23** [twitter/util#132]
Hi,

For the past 3 days we have been experiencing a lot of issues with some transitive dependencies of Twitter projects. As our entire eco-system is basically made of Twitter OSS, a vast majority of things are failing beyond our control and we do not mirror ```maven.twttr.com```.

Long story short, could you think of any reason why the following would fail to resolve? I will add that multiple CI systems have been tried and even local machines fail to resolve things after tens of manual retries.

- Our Phantom project Travis CI build log [here](https://travis-ci.org/websudos/phantom)

Specifically:

```scala

[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: com.twitter.common.zookeeper#server-set;1.0.83: not found
[warn] 	:: com.twitter.common#util-system-mocks;0.0.81: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn] 	Note: Unresolved dependencies path:
[warn] 		com.twitter.common.zookeeper:server-set:1.0.83
[warn] 		  +- com.twitter:util-zk-common_2.11:6.23.0
[warn] 		  +- com.twitter:finagle-serversets_2.11:6.24.0
[warn] 		  +- com.websudos:util-zookeeper_2.11:0.6.12 (/home/ubuntu/phantom/project/PhantomBuild.scala#L282)
[warn] 		  +- com.websudos:phantom-zookeeper_2.11:1.8.1
[warn] 		com.twitter.common:util-system-mocks:0.0.81
[warn] 		  +- com.twitter.common:base:0.0.95
[warn] 		  +- com.twitter.common:application-action:0.0.75
[warn] 		  +- com.twitter.common:stats:0.0.98
[warn] 		  +- com.twitter.common:util:0.0.106
[warn] 		  +- com.twitter.common.zookeeper:group:0.0.78
[warn] 		  +- com.twitter:util-zk-common_2.11:6.23.0
[warn] 		  +- com.twitter:finagle-serversets_2.11:6.24.0
[warn] 		  +- com.websudos:util-zookeeper_2.11:0.6.12 (/home/ubuntu/phantom/project/PhantomBuild.scala#L282)
[warn] 		  +- com.websudos:phantom-zookeeper_2.11:1.8.1

```

**Comment by travisbrown** [comment]
These issues have been affecting our open source builds as well, and the internal team responsible for the `maven.twttr.com` repository is investigating the problem. They're hoping to have a fix soon, but in the meantime there are a couple of fairly reasonable workarounds. One is to add a line like this to your Travis config:

``` yaml
before_script: travis_retry sbt ++$TRAVIS_SCALA_VERSION update
```

This will turn on (three) retries for resolution and downloading only. This seems to be enough to get around the intermittent errors in many cases, and since only the `update` task is retried, it won't really slow down builds that fail for other reasons.

You can also cache artifacts across builds like this:

``` yaml
cache:
  directories:
    - $HOME/.ivy2/cache
```

In the longer term, these failures are yet another motivation for us finally to get rid of this repository and publish these artifacts to Maven Central. I don't have any kind of definite timeline for this, but I'll update this issue as we know more.

**Comment by travisbrown** [comment]
The issue with `maven.twttr.com` has been resolved (at least we have a fix that seems to work on all the cases I've tried or heard of), so you shouldn't need the workarounds any longer. Please reopen if you continue to see failures.
