### ISSUE TITLE
ZkClient thread safety

### ISSUE THREAD

**Issue by IrimieBogdan** [twitter/util#217]
We are experiencing issues with ZkClient in a multi threaded environment.  We are using `monitorTree()` and `getData.monitor()` to track changes in ZK structure. If we are reading data from zookeeper and at the same time the monitor is triggered, the client blocks.

Is the ZkClient thread safe?

**Comment by mosesn** [comment]
@IrimieBogdan to be honest, we don't know very much about util-zk because we don't use it very widely inside of Twitter anymore.  I would not be surprised that it doesn't work anymore.  Unfortunately, the right solution might be to switch to a different ZK client library.  We're currently auditing util to remove pieces that we are no longer confident in, and I think util-zk may be on the chopping block.  With that said, if you have time to chase down the issue, we would love a PR, but it might be more expedient to switch to a zk library that's more actively maintained, like curator.
