### ISSUE TITLE
for first timers - is it expected you write code contributions with your issues, or can you also just do docs?

### ISSUE THREAD

**Issue by dhope-lab** [twitter/util#282]
One line summary of the issue here.

### Expected behavior

As concisely as possible, describe the expected behavior.

### Actual behavior

As concisely as possible, describe the observed behavior.

### Steps to reproduce the behavior

Please list all relevant steps to reproduce the observed behavior.

**Comment by ryanoneill** [comment]
If you're asking whether you can contribute to our open source projects (util/finagle/scrooge/twitter-server/finatra) by updating documentation, absolutely. 

If you're asking whether if you report an issue whether you'll be expected to contribute code to fix it, no not particularly. We try to give people the opportunity to fix something that they report though. Also, if it's a feature request, or the expansion of a feature that we're not planning on working anytime soon, we may ask the reporter to work on it because otherwise it may be a long time before any of us get to it.

Hope that answers your question. If not, please follow up. Thanks.

**Comment by cacoco** [comment]
@huhwhy thanks for the question! This is an open source project and as such the expectation is that a PR to change anything in the repository is fair game, this would include documentation updates and improvements or changes. If you look in the commit history, I'm sure you'll find PRs that simply fixed typos or incorrect documentation contained herein. Hope that answers your question. Thanks!
