### ISSUE TITLE
Provide a way to shutdown Closable.collectorThread

### ISSUE THREAD

**Issue by jedws** [twitter/util#99]
When running in a plugin environment, it is necessary to shutdown all threads a plugin has started.

`Closable.collectorThread` isn't exposed and thus cannot be shutdown via any lifecycle API.

A workaround is to throw a fatal error from a `Closable` that is registered using the 'Closable.closeOnCollect(Closable, Object)` method, but this has no ordering guarantees.

A more friendly approach would use an appropriate `ExecutorService` that only created a thread if one wasn't available, and died when not in use.

**Comment by mosesn** [comment]
@jedws I assume that this is no longer a problem for you, since there hasn't been movement on this ticket in two years.  I think it works as expected for most of our users, since it's a daemon thread.  I'm going to close it for now, but please feel free to open it if you're still running into this problem.

**Comment by jedws** [comment]
It is not a problem for us as we stopped using it, partly due to this bug.

**Comment by mosesn** [comment]
Ahh, too bad.  Good to know that util doesn't do well in a plugin environment, thanks for the feedback!
